ADDRESS = '127.0.0.1'
PORT = 8000
COMMAND_SIZE = 5
END = "END  "
MSG_SIZE = 40
N_BYTES = 2
STRING_ENCODING = 'utf-8'
X_MAX = "max x"
Y_MAX = "max y"
get_Players = "gt_Pl"
get_nr_Players ="g_n_P"
get_Obstacles = "gt_Ob"
get_nr_Obstacles ="g_n_O"
execute = "e"
new_Player = "np"